### PR TITLE
Small compatibility fixes

### PR DESCRIPTION
**Pull request by dwmw2**
- Echo input from non-tty stdin
- Fix Ctrl-R key handling
- Simple build fixes

### CODE REVIEW

**Comment by msteveb** [comment]
Thanks. C++ support seems fine.

What is the rationale for echoing input. If I do this I get double output. One from the terminal and one from the echo.

```
$ TERM=dumb ./jimsh
Welcome to Jim version 0.80
. puts hello
puts hello
hello
```

Regarding reverse-i-search, really - is that how it is supposed to work? How to go forward again after skipping past the one you want? I suppose we have to be compatible, but I prefer mine :-(

**Comment by dwmw2** [comment]
> What is the rationale for echoing input. If I do this I get double output. One from the terminal and one from the echo.

Ah, as noted in the commit comment, this was intended for the case where it *isn't* a tty. I hadn't spotted that `enableRawMode()` is also returning failure (and even setting `errno = ENOTTY` for the case of unsupported `$TERM` too.

I'm a little confused by the errno setting... can I make `enableRawMode()` set `errno = ENOTTY` only when it literally isn't a tty, and set a different errno in other cases.... or in fact, is anyone even looking? Why set errno at all?

**Comment by dwmw2** [comment]
> Regarding reverse-i-search, really - is that how it is supposed to work? How to go forward again after skipping past the one you want? I suppose we have to be compatible, but I prefer mine :-(

Honestly, this is one of those cases where my fingers' muscle memory knows more than my conscious brain. They *definitely* want that repeated Ctrl-R to keep going backwards. 

It turns out that Ctrl-S is the 'search forwards' command, which doesn't actually work in practice unless you do `stty -ixon` otherwise it gets consumed. But I'll go and implement that; thanks for the reminder.

**Comment by msteveb** [comment]
> Or just do this perhaps...
> 
> ```
> --- a/linenoise.c
> +++ b/linenoise.c
> @@ -1851,7 +1851,7 @@ char *linenoise(const char *prompt)
>          printf("%s", prompt);
>          fflush(stdout);
>          sb = sb_getline(stdin);
> -        if (sb) {
> +        if (!isatty(current.fd) && sb) {
>              printf("%s\n", sb_str(sb));
>              fflush(stdout);
>          }
> ```

Yes. That will probably do. Use of errno is probably lost in the mists of time (not literally - it would have come from original linenoise).

**Comment by msteveb** [comment]
With the ^S change, I think this all looks good but will take some time before I can test thoroughly and merge (busy time leading up to Christmas) so I'll get to it in due course. Thanks.

**Comment by dwmw2** [comment]
Branch updated and rebased, updated the list of keybindings that you've added in the meantime. Also added @metinkaya's allocation checks from https://github.com/dwmw2/linenoise/pull/1

**Comment by msteveb** [comment]
Thanks. I will get to this soon but I won’t be merging the allocation checks. IMHO checking for allocation failure achieves no useful purpose on modern operating systems.

**Comment by msteveb** [comment]
I merged the earlier commits and made a few small changes to ctrl-r/s
Take a look at https://github.com/msteveb/linenoise/tree/readline-compat-ctrl-r and if ok I will merge it

**Comment by msteveb** [comment]
I didn't get a response, so I merged that branch. Any problems can be raised in a new issue.

**Pull request closed without merging**
