### PR TITLE
Supported Non-English character input and display on Windows

### PR DESCRIPTION
**Pull request by jenson-shi**
Fixed compiler error on MSVC.
Non-English character input and display when Windows platform defined USE_UTF8.

### CODE REVIEW

**Comment by msteveb** [comment]
Thanks. I've taken the compile fix, but can you explain why the changes to outputChars() and refreshLine() are correct? I am unable to get Windows to either input or output utf-8 in any sensible manner either with or without this change, so I'm not able to test it.

**Comment by jenson-shi** [comment]
The default settings for the Windows console cannot display UTF8 character, when you enter a Non English character, the linenoise echo is not a human readable character. So I convert UTF8 to UTF16 for echo on Windows console.

Non-English character may need to skip 2 character position such as Chinese otherwise the cursor will be displayed in half character position. This bug not only on Windows, The same problem on Mac OS X & Linux.

I have a screenshot, first line is fixed UTF8 echo, second line is just printf a UTF8 string from linenoise, third line is displayed cursor in UTF8 string.
[linenoise-win32](http://pan.baidu.com/s/1jI57x6A)

You can try these characters "中文测试" on your system, copy-paster and move LEFT or RIGHT key.

**Comment by jenson-shi** [comment]
And I found another problem, in UTF8 mode cannot auto-completion on Mac OS X & Linux. linenoise is just display ^I
[linenoise-linux-cannot-auto-completion](http://pan.baidu.com/s/1skYjjp7)

**Comment by msteveb** [comment]
There are a few different issues here:

1. It seems we need to use WriteConsoleOutputCharacterW() to reliably output the windows console.
2. The current utf-8 implementation has no support for combining characters. I see that there is support for combing characters here: https://github.com/yhirose/linenoise/blob/utf8-support/encodings/utf8.c
3. Did you remove -DNO_COMPLETION to enable tab completion?

**Comment by jenson-shi** [comment]
Sorry, I neglect the content of Makefile. I removed -DNO_COMPLETION and it runs normally.

**Comment by msteveb** [comment]
Thanks! I made the checks for display width more efficient and fixed the output when wide characters are combined with control characters, but I kept you as the author for for the main changes. Please check out latest git and make sure it works for you.

**Comment by jenson-shi** [comment]
Thanks! It's worked fine.

**Pull request closed without merging**
